spring.application.name=todolist

# Conexão SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=dt_todolist;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=MinhaSenha@2026!

# Driver
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Mostrar SQL
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update